var aTop2data = [
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/s21-1.png",
			name:"小米CC9",
			price:"1699元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s21-2.png",
			name:"小米CC9e",
			price:"1299元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s21-3.png",
			name:"小米CC9 美图定制版",
			price:"2599元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s21-4.png",
			name:"小米9",
			price:"2799元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s21-5.png",
			name:"小米MIX 3",
			price:"2599元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s21-6.webp",
			name:"小米MIX 2S",
			price:"1799元起"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/s22-1.webp",
			name:"Redmi Note 8 Pro",
			price:"1399元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s22-2.webp",
			name:"Redmi Note 8",
			price:"999元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s22-3.jpg",
			name:"Redmi K20 Pro",
			price:"2299元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s22-4.jpg",
			name:"Redmi K20",
			price:"1799元起"
		},
		{
			
			url:"https://www.kuazhu.con",
			img:"images/s22-5.jpg",
			name:"Redmi Note 7 Pro",
			price:"1399元起"
		},
		{
			
			url:"https://www.kuazhu.con",
			img:"images/s22-6.jpg",
			name:"Redmi 7A",
			price:"579元起"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/s23-1.webp",
			name:"Redmi 红米电视4A 70英寸 R70A",
			price:"3799元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s23-2.jpg",
			name:"小米壁画电视 65英寸",
			price:"6999元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s23-3.jpg",
			name:"小米全面屏电视E55A",
			price:"1799元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s23-4.png",
			name:"小米电视4A 32英寸",
			price:"699元起"
		},{
			
			url:"https://www.kuazhu.con",
			img:"images/s23-5.jpg",
			name:"小米电视4A 55英寸",
			price:"1699元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s23-6.jpg",
			name:"小米电视4A 65英寸",
			price:"2699元起"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"4小米CC9",
			price:"1794元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"4小米CC9",
			price:"1794元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"4小米CC9",
			price:"1794元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"4小米CC9",
			price:"1794元起"
		},
		{
			
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"4小米CC9",
			price:"1794元起"
		},
		{
			
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"4小米CC9",
			price:"1794元起"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"5小米CC9",
			price:"1795元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"5小米CC9",
			price:"1795元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"5小米CC9",
			price:"1795元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"5小米CC9",
			price:"1795元起"
		},{
			
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"5小米CC9",
			price:"1795元起"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"6小米CC9",
			price:"1796元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"6小米CC9",
			price:"1796元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"6小米CC9",
			price:"1796元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"6小米CC9",
			price:"1796元起"
		},{
			
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"6小米CC9",
			price:"1796元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"6小米CC9",
			price:"1796元起"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"7小米CC9",
			price:"1797元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"7小米CC9",
			price:"1797元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"7小米CC9",
			price:"1797元起"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"7小米CC9",
			price:"1797元起"
		},
		{
			
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"7小米CC9",
			price:"1797元起"
		}
	]
]
var aTop3data = [
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-01.webp",
			name:"Redmi Note8 Pro"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-02.png",
			name:"小米9 SE"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-03.jpg",
			name:"Redmi K20 Pro"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-04.jpg",
			name:"移动4G+专区"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-05.webp",
			name:"Redmi Note8"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-06.png",
			name:"小米MIX 3"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-07.webp",
			name:"Redmi K20"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-08.jpg",
			name:"小米移动 电话卡"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-09.png",
			name:"小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-10.png",
			name:"小米MIX 2S"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-11.jpg",
			name:"Redmi 7A"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-12.png",
			name:"手机上门维修"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-13.png",
			name:"小米CC美图定制版"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-14.png",
			name:"小米MAX 3"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-15.png",
			name:"Redmi 7"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-16.jpg",
			name:"云服务空间月卡"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-17.png",
			name:"小米CC9e"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-18.webp",
			name:"黑鲨手机2 Pro"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-19.jpg",
			name:"Redmi Note7 Pro"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-20.jpg",
			name:"米粉卡 日租卡"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-21.png",
			name:"小米9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-22.webp",
			name:"黑鲨游戏手机2"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s3-23.png",
			name:"Redmi Note7"
		}
		// ,
		// {
		// 	url:"https://www.kuazhu.con",
		// 	img:"images/shouji01.jpg",
		// 	name:"1小米CC9"
		// }
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-01.webp",
			name:"Redmi 红米电视 70英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-02.png",
			name:"小米电视4A 43英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-03.png",
			name:"小米电视4C 50英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-04.png",
			name:"小米电视4 55英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-05.jpg",
			name:"小米壁画电视 65英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-06.png",
			name:"小米电视4A 55英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-07.png",
			name:"小米电视4C 50英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-08.jpg",
			name:"小米电视4 65英寸旗舰版"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-09.jpg",
			name:"小米全面屏电视"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-10.png",
			name:"小米电视4A 58英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-11.jpg",
			name:"小米电视4C 55英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-12.jpg",
			name:"小米电视4 75英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-13.png",
			name:"小米电视4A 32英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-14.png",
			name:"小米电视4A 65英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-15.png",
			name:"小米电视4X 43英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-16.png",
			name:"小米电视4S"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-17.png",
			name:"小米电视4A 43英寸青春版"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-18.png",
			name:"小米电视4C 32英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-19.png",
			name:"小米电视4X 55英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-20.png",
			name:"小米电视体育版"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-21.jpg",
			name:"小米电视4A 49英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-22.jpg",
			name:"小米电视4C 40英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-23.jpg",
			name:"小米电视4A 65英寸"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/s32-24.jpg",
			name:"小米盒子"
		}
	],		
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		}
	],
	[
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		},
		{
			url:"https://www.kuazhu.con",
			img:"images/shouji01.jpg",
			name:"1小米CC9"
		}
	]
]	
var aTop8data = [
	[
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"4699元",
		del:"799元",
		flag:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}	
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"4699元",
		del:"799元",
		flagN:'新品',
		// pl:{
		// 	content:"我是当评论的，谢谢",
		// 	author:"奥特曼"
		// 	}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"4699元",
		del:"799元",
		flagJ:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"4699元",
		del:"799元",
		flag:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"4699元",
		del:"799元",
		flagJ:'立减200元',
		// pl:{
		// 	content:"我是当评论的，谢谢",
		// 	author:"奥特曼"
		// 	}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"4699元",
		del:"799元",
		flag:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"4699元",
		del:"799元",
		flagJ:'立减200元',
		// pl:{
		// 	content:"我是当评论的，谢谢",
		// 	author:"奥特曼"
		// 	}
		},
		{		
			top:{
				url:"https://www.kuazhu.con",
				price:"299元",
				name:"米家电烤箱",
				img:"images/dkx.jpg"
			},
			bottom:{
				url:"https://www.kuazhu.con",
				price:"热门",
				name:"浏览更多",
				ides:"&#xe615;"
			}
		}
	],
	[
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"2699元",
		del:"799元",
		flagN:'新品',
		// pl:{
		// 	content:"我是当评论的，谢谢",
		// 	author:"奥特曼"
		// 	}	
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"2699元",
		del:"799元",
		flagN:'新品',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"2699元",
		del:"799元",
		flag:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"2699元",
		del:"799元",
		flagJ:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"2699元",
		del:"799元",
		flagJ:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"2699元",
		del:"799元",
		flagN:'新品',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"2699元",
		del:"799元",
		flagJ:'立减200元',
		// pl:{
		// 	content:"我是当评论的，谢谢",
		// 	author:"奥特曼"
		// 	}
		},
		{		
			top:{
				url:"https://www.kuazhu.con",
				price:"299元",
				name:"米家电烤箱",
				img:"images/dkx.jpg"
			},
			bottom:{
				url:"https://www.kuazhu.con",
				price:"电脑",
				name:"浏览更多",
				ides:"&#xe615;"
			}
		}
	],
	[
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"3699元",
		del:"799元",
		flag:'立减200元',
		// pl:{
		// 	content:"我是当评论的，谢谢",
		// 	author:"奥特曼"
		// 	}	
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"3699元",
		del:"799元",
		flagJ:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"3699元",
		del:"799元",
		flag:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"3699元",
		del:"799元",
		flagJ:'立减200元',
		// pl:{
		// 	content:"我是当评论的，谢谢",
		// 	author:"奥特曼"
		// 	}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"3699元",
		del:"799元",
		flag:'立减200元',
		// pl:{
		// 	content:"我是当评论的，谢谢",
		// 	author:"奥特曼"
		// 	}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"3699元",
		del:"799元",
		flagN:'新品',
		// pl:{
		// 	content:"我是当评论的，谢谢",
		// 	author:"奥特曼"
		// 	}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"3699元",
		del:"799元",
		flag:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{		
			top:{
				url:"https://www.kuazhu.con",
				price:"299元",
				name:"米家电烤箱",
				img:"images/dkx.jpg"
			},
			bottom:{
				url:"https://www.kuazhu.con",
				price:"电视影音",
				name:"浏览更多",
				ides:"&#xe615;"
			}
		}
	],
	[
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"1699元",
		del:"799元",
		flagJ:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}	
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"1699元",
		del:"799元",
		flagN:'新品',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"1699元",
		del:"799元",
		flag:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"1699元",
		del:"799元",
		flagJ:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"1699元",
		del:"799元",
		flag:'立减200元',
		// pl:{
		// 	content:"我是当评论的，谢谢",
		// 	author:"奥特曼"
		// 	}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"1699元",
		del:"799元",
		flagN:'新品',
		// pl:{
		// 	content:"我是当评论的，谢谢",
		// 	author:"奥特曼"
		// 	}
		},
		{
		url:"https://www.kuazhu.con",
		img:"images/jiadian01.jpg",
		name:"小米电视4A 32英寸",
		des:"64位四核处理器/1GB+4GB大内存",
		price:"1699元",
		del:"799元",
		flag:'立减200元',
		pl:{
			content:"我是当评论的，谢谢",
			author:"奥特曼"
			}
		},
		{		
			top:{
				url:"https://www.kuazhu.con",
				price:"299元",
				name:"米家电烤箱",
				img:"images/dkx.jpg"
			},
			bottom:{
				url:"https://www.kuazhu.con",
				price:"家居",
				name:"浏览更多",
				ides:"&#xe615;"
			}
		}
	]
]	
					